vim.keymap.set("n", "<leader>N", vim.cmd.Ex, { desc = "Netwr" })
vim.keymap.set("n", "x", '"_x')
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open buffer diagnostic [q]uickfix list" })
vim.keymap.set("n", "<leader>Q", vim.diagnostic.setqflist, { desc = "Open project diagnostic [Q]uickfix list" })
vim.keymap.set("n", "<leader>D", vim.diagnostic.open_float, { desc = "[D]iagnostic message" })
